// Hardware Info
export const RECEIVE_HARDWARE_INFO = 'RECEIVE_HARDWARE_INFO';
export const STOP_TRACKING_HARDWARE_INFO = 'STOP_TRACKING_HARDWARE_INFO';
// Mining
export const SELECT_MINER = 'SELECT_MINER';
export const SET_MINING_SPEED = 'SET_MINING_SPEED';
export const START_MINING = 'START_MINING';
export const STOP_MINING = 'STOP_MINING';
